artifact_location: /home/liujifuwork/workspace/Color_Calibration/model_yolo_secondary/runs/mlflow/565032362935851438
creation_time: 1739495437198
experiment_id: '565032362935851438'
last_update_time: 1739495437198
lifecycle_stage: active
name: runs/train
