artifact_location: /home/liujifuwork/workspace/Color_Calibration/model_yolo/runs/mlflow/0
creation_time: 1739413626467
experiment_id: '0'
last_update_time: 1739413626467
lifecycle_stage: active
name: Default
